app:
    name: register

spring:
  application:
    name: eureka


---
spring:
  profiles: peer1

server:
    port: 9080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
       defaultZone: http://localhost:9070/eureka/

---
spring:
  profiles: peer2

server:
    port: 9070

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
       defaultZone: http://localhost:9080/eureka/