app:
    name: autumn

server:
    port: 9081

eureka:
  client:
    service-url:
       defaultZone: http://localhost:9080/eureka/,http://localhost:9070/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: autumn
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411


logging:
  level: info

